runtime: go
api_version: go1

handlers:

- url: /.*
  script: _go_app

env_variables:
 CLOUDSQL_CONNECTION_NAME: golang-programming-test:us-central1:test
 CLOUDSQL_USER: root
 CLOUDSQL_PASSWORD: 'mCnP92714'